version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./hesk:/var/www/html
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.25.0.7

  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hesk
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      my_network:
        ipv4_address: 172.25.0.5
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.25.0.6

networks:
  my_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/24
         gateway: 172.25.0.253